### ISSUE TITLE
Trusted Auctioneer task list

### ISSUE THREAD

**Issue by bharath-123** [astriaorg/flame#1]
### Tasks
```[tasklist]
- [ ] implement the ExecuteOptimsticBlock grpc method which receives an optimistic block from Trusted Auctioneer, executes it to maintain a separate optimistic fork.
- [ ] Implement the NewOptimisticBlockEvent  which is sent when an optimistic block is created
- [ ] Implement listening to the NewOptimisticBlockEvent  rather than NewChainHeadEvent in Reset
- [ ] Implement mempool clearing in demoteUnexecutables  in Reset
- [ ] Implement the MempoolClearedEvent which is sent when the mempool is cleared
- [ ] Implement the StreamBundles grpc method which listens to transactions via the SubscribeNewTxsEvent and streams the resulting transactions
- [ ] Add metrics

```
